config/routes.rb
Rails.application.routes.draw do
  post "/rate", to: "rater#create", as: "rate"
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  scope "(:locale)", locale: /en|vi/ do
    root to: "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"

    devise_scope :user do
      resources :users do
        resources :borrows
        member do
          get :following, :followers
        end
      end
    end

    resources :follow_books, only: [:create, :destroy]
    resources :relationships, only: [:create, :destroy]
    resources :like_books, only: [:create, :destroy]

    resources :books, only: %i(index show) do
      resources :comments, only: [:create, :destroy]
    end
    namespace :admin do
      resources :users
      resources :books
      resources :borrows
      resources :categories
      resources :statistics, only: [:index]
    end
  end
end

app/models/book.rb
class Book < ApplicationRecord
  ratyrate_rateable "like", "good"
  enum status: %i(ready borrowed)

  has_many :authors_books, dependent: :destroy
  has_many :authors, through: :authors_books, dependent: :destroy
  has_many :borrows, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :follow_books, dependent: :destroy
  has_many :like_books, dependent: :destroy

  belongs_to :category
  belongs_to :publisher
  default_scope -> {order(created_at: :desc)}
  scope :select_attr, ->{select(:id, :category_id, :publisher_id, :name, :content, :number_of_page, :status, :image)}
  mount_uploader :image, ImageUploader
  accepts_nested_attributes_for :authors_books, allow_destroy: true,
    reject_if: proc{|attributes| attributes["author_id"] == "0"}

  delegate :name, :phone, :address, to: :publisher, prefix: true
  delegate :name, to: :category, prefix: true

  class << self
    def to_csv
      CSV.generate do |csv|
        attributes = %w{id name category_id publisher_id content number_of_page status}
        csv << attributes
        all.each do |book|
          csv << book.attributes.values_at(*attributes)
        end
      end
    end
  end
end

app/controllers/admin/books_controller.rb
module Admin
  class BooksController < BaseController
    before_action :find_book, except: %i(index create new)

    def index
      @q = Book.ransack params[:q]
      @books = @q.result(distinct: true).page(params[:page]).per Settings.per_page
      respond_to do |format|
        format.html
        format.csv {send_data Book.ransack(name_or_content_or_publisher_name_or_authors_name_cont: params[:q])
          .result(distinct: true).to_csv}
        format.xls {send_data Book.ransack(name_or_content_or_publisher_name_or_authors_name_cont: params[:q])
          .result(distinct: true).to_csv}
      end
    end

    def new
      @book = Book.new
      @authors = Author.select_attr
    end

    def show; end

    def edit
      @authors = Author.select_attr
    end

    def update
      if @book.update book_params
        flash[:success] = "update_success"
        redirect_to admin_books_path
      else
        flash[:danger] = "update_fail"
        render :edit
      end
    end

    def destroy
      if @book.destroy
        flash[:success] = "destroy_succsess"
      else
        flash[:danger] = "destroy_fail"
      end
      redirect_to admin_books_path
    end

    def create
      @book = Book.new book_params
      if @book.save
        flash[:success] = t "books.created"
      else
        flash[:danger] = t "books.create_fail"
      end
      redirect_to admin_books_path
    end

    private

    def book_params
      params.require(:book).permit :category_id, :publisher_id, :name, :content,
        :number_of_page, :status, :image, authors_books_attributes: %i(id book_id author_id _destroy)
    end

    def find_book
      return if @book = Book.find_by(id: params[:id])
      flash[:danger] = t "books.find_fail"
      redirect_to admin_books_path
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, except: %i(index)
  before_action :status_follow_book, :status_like_book, only: %i(show)

  def index
    @q = Book.ransack params[:q]
    @books = @q.result(distinct: true)
    @panigatable = Kaminari.paginate_array(@books).page(params[:page]).per Settings.book_per_page
    @categories = Category.select_attr
    respond_to do |format|
      format.html {}
      format.csv { send_data Book.ransack(name_or_content_or_publisher_name_or_authors_name_cont: params[:q])
        .result(distinct: true).to_csv }
      format.xls { send_data Book.ransack(name_or_content_or_publisher_name_or_authors_name_cont: params[:q])
        .result(distinct: true).to_csv }
    end
  end

  def show
    @comments = @book.comments.order_comment
    return unless user_signed_in?
    @borrow = current_user.borrows.new
    @comment = current_user.comments.build
  end

  private

  def find_book
    return if @book = Book.find_by(id: params[:id])
    flash[:danger] = t "books.find_fail"
    redirect_to books_path
  end

  def status_follow_book
    return unless user_signed_in?
    @follow_book = @book.follow_books.find_by(book_id: @book.id) || @book.follow_books.build
  end

  def status_like_book
    return unless user_signed_in?
    @like_book = @book.like_books.find_by(book_id: @book.id) || @book.like_books.build
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def status_choice
    Book.statuses.keys.map{|status| [t("#{status}"), status]}
  end
end

app/views/admin/books/_book.html.erb
<tr>
  <td class="row"><%= book_counter + Settings.counter %></td>
  <td><%= image_tag book.image_url %></td>
  <td><%= link_to book.name, admin_book_path(book) %></td>
  <td><%= book.category_name %></td>
  <td><%= book.publisher_name %></td>
  <td><%= book.number_of_page %></td>
  <td><%= book.status %></td>
  <td><%= link_to t("comments.delete"), admin_book_path(book),method: :delete,
    data: {confirm: t("comments.you_sure")}, class: "btn btn-danger" %></td>
</tr>

app/views/admin/books/_form.html.erb
<div class="right_col" role="main">
  <div>
    <div class="page-title">
      <div class="title_left">
        <h3><%= t "books.create" %></h3>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_content">
            <%= form_for [:admin, @book], id: "demo-form2", class: "form-horizontal form-label-left" do |f| %>
              <div class="avatar-upload col-sm-3">
                <div class="avatar-edit">
                  <%= f.file_field :image, id: "imageUpload" %>
                  <label for="imageUpload"></label>
                </div>
                <div class="avatar-preview">
                  <div id="imagePreview"></div>
                </div>
              </div>
              <div class="col-sm-7 margin-left-55">
                <div class="form-group">
                  <%= f.label :category, t("books.category_name"), class: "control-label col-sm-3" %>
                  <div class=" col-sm-9">
                    <%= f.select :category_id, category_choices, class: "form-control " %>
                  </div>
                </div></br>
                <div class="form-group">
                  <%= f.label :publisher, t("books.publisher_name"), class: "control-label col-sm-3" %>
                  <div class=" col-sm-9">
                    <%= f.select :publisher_id, publisher_choices, class: "form-control " %>
                  </div>
                </div></br>
                <div class="form-group">
                  <%= f.label :book_name, t("books.name"), class: "control-label col-sm-3" %>
                  <div class=" col-sm-9">
                    <%= f.text_field :name, class: "form-control" %>
                  </div>
                </div></br>
                <div class="form-group">
                  <%= f.label :content, t("books.content"), class: "control-label col-sm-3" %>
                  <div class=" col-sm-9">
                    <%= f.text_area :content, class: "form-control" %>
                  </div>
                </div></br></br>
                <div class="form-group">
                  <%= f.label :number_of_page, t("books.number_of_page"), class: "control-label col-sm-3" %>
                  <div class=" col-sm-9">
                    <%= f.number_field :number_of_page, class: "form-control" %>
                  </div>
                </div></br>
                <div class="form-group" data-length="<%= authors.length %>" id="length">
                  <%= f.label :author, t("books.author"), class: "control-label col-sm-3" %>
                  <div class="col-sm-9">
                    <% authors.each do |author| %>
                      <%= f.fields_for :authors_books,
                        author.author_ids_of_book(@book) ||
                        @book.authors_books.build do |ap| %>
                        <div class="col-sm-6 ">
                          <%= f.label author.name %>
                          <%= ap.check_box :author_id, {id: "checkbox_check#{author.id}",
                            class: "checkbox2"}, author.id %>
                          <%= ap.hidden_field :_destroy, id: "data-form-prepend#{author.id}" %>
                        </div>
                      <% end %>
                    <% end %>
                  </div>
                </div>
                </br>
                <div class="form-group">
                  <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                    <%= f.submit t("submit"), class: "btn btn-success" %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/books/edit.html.erb
<%= render "form", authors: @authors %>

app/views/admin/books/index.html.erb
<div class="right_col" role="main">
  <div>
    <div class="page-title">
      <%= render 'layouts/admin/flash' %>
      <div class="title_left">
        <h3><%= t "admins.books" %></h3>
      </div>
      <div>
        <div class="col-md-4 col-sm-4 col-xs-12 form-group pull-right top_search">
          <%= search_form_for [:admin, @q], method: :get do |f| %>
            <div class="input-group">
              <%= f.search_field :name_or_content_or_publisher_name_or_authors_name_cont, class: "form-control", placeholder: t("search.users") %>
              <span class="input-group-btn">
                <%= f.submit t("books.search"), class: "btn btn-default" %>
              </span>
            </div>
          <% end %>
        </div>
        <div class="col-sm-2 pull-right">
          <%= link_to t("books.create"), new_admin_book_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_content">
          <% if @books.any? %>
            <div class="book-exort">
              <p class="col-sm-2 pull-right export">
              <%= t "export.download" %>
              <%= link_to t("export.csv"), admin_books_path(format: "csv", q: q_params(params[:q])) %> |
              <%= link_to t("export.excel"), admin_books_path(format: "xls", q: q_params(params[:q])) %></p>
            </div>
            <table class="table">
              <thead>
                <tr>
                  <th>#</th>
                  <th><%= t "books.image" %></th>
                  <th><%= t "books.name" %></th>
                  <th><%= t "books.category_name" %></th>
                  <th><%= t "books.publisher_name" %></th>
                  <th><%= t "books.number_of_page" %></th>
                  <th><%= t "borrows.status" %></th>
                </tr>
              </thead>
              <tbody>
                <%= render @books %>
              </tbody>
            </table>
            <% end %>
            <div class="col-sm-8 col-sm-offset-3">
              <%= paginate @books, theme: "twitter-bootstrap-3" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/books/new.html.erb
<%= render "form", authors: @authors %>

app/views/admin/books/show.html.erb
<div class="right_col" role="main">
  <div>
    <div class="row top_tiles" style="margin: 10px 0;">
      <div class="col-md-12 col-sm-12 col-xs-12 tile">
        <aside class="col-md-4">
          <section class="user_info">
            <h3>
              <%= @book.name %>
            </h3>
            <h5>
              <%= @book.category_name %>
              <%= @book.publisher_name %>
              <%= @book.number_of_page %>
              <%= @book.status %>
            </h5>
          </section>
          <p>
            <%= link_to t("users.edit"), edit_admin_book_path(@book) %>
          </p>
        </aside>
      </div>
    </div>
  </div>
</div>