config/routes.rb
Rails.application.routes.draw do
  post "/rate", to: "rater#create", as: "rate"
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  scope "(:locale)", locale: /en|vi/ do
    root to: "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"

    devise_scope :user do
      resources :users do
        resources :borrows
        member do
          get :following, :followers
        end
      end
    end

    resources :follow_books, only: [:create, :destroy]
    resources :relationships, only: [:create, :destroy]
    resources :like_books, only: [:create, :destroy]

    resources :books, only: %i(index show) do
      resources :comments, only: [:create, :destroy]
    end
    namespace :admin do
      resources :users
      resources :books
      resources :borrows
      resources :categories
      resources :statistics, only: [:index]
    end
  end
end

app/views/layouts/admin/_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "admin/application", media: "all",
  "data-turbolinks-track": true %>
<%= javascript_include_tag "admin/application" %>

app/views/layouts/admin/_flash.html.erb
<% flash.each do |message_type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/layouts/admin/_footer.html.erb
<footer>
  <div class="pull-right">
    <%= t "app.name" %>
  </div>
  <div class="clearfix"></div>
</footer>

app/views/layouts/admin/_header.html.erb
<div class="top_nav">
  <div class="nav_menu">
    <nav>
      <div class="nav toggle">
        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <%= t "layouts.header.account" %>
            <span class=" fa fa-angle-down"></span>
          </a>
          <ul class="dropdown-menu dropdown-usermenu pull-right">
            <li><%= link_to t("layouts.header.profile"), current_user %></li>
            <li>
              <%= link_to t("layouts.header.settings"), "#" %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out pull-right"></i><%= t "layouts.header.log_out" %></a>
              <% end %>
            </li>
          </ul>
        </li>
        <li>
            <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
              <%= t "languages.language" %>
              <span class=" fa fa-angle-down"></span>
            </a>
            <ul class="dropdown-menu dropdown-usermenu pull-right">
              <li><%= link_to t("languages.en"), url_for(locale:"en"), class: "dropdown-item" %></li>
              <li><%= link_to t("languages.vi"), url_for(locale:"vi"), class: "dropdown-item" %></li>
            </ul>
          </li>
        <li role="presentation" class="dropdown">
          <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
            <i class="fa fa-envelope-o"></i>
            <span id="notification-counter" class="badge bg-red"><%= notifications.count :id %></span>
          </a>
          <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
            <%= render notifications %>
            <li><%= link_to t("layouts.header.read_all"), admin_borrows_path %></li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</div>

app/views/layouts/admin/_menu.html.erb
<div class="col-md-3 left_col">
  <div class="left_col scroll-view">
    <div class="navbar nav_title" style="border: 0;">
      <a href="index.html" class="site_title"><i class="fa fa-paw"></i>
        <span><%= t "app.name" %></span></a>
    </div>
    <div class="clearfix"></div>
    <div class="profile clearfix">
      <div class="profile_pic">
        <%= image_tag current_user.gravatar_url, class: "img-circle profile_img" %>
      </div>
      <div class="profile_info">
        <span><%= t "admins.welcome" %></span>
        <h2><%= link_to current_user.name, current_user %></h2>
      </div>
    </div>
    <br />
    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
      <div class="menu_section">
        <ul class="nav side-menu">
          <li><a><i class="fa fa-bars"></i> <%= t "admins.menu" %> <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><%= link_to t("admins.statistic"), admin_statistics_path %></li>
              <li><%= link_to t("admins.users"), admin_users_path %></li>
              <li><%= link_to t("admins.borows"), admin_borrows_path %></li>
              <li><%= link_to t("admins.books"), admin_books_path %></li>
              <li><%= link_to t("admins.categories"), admin_categories_path %></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/admin/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :page_title %></title>
    <%= render "layouts/admin/default" %>
  </head>
  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <%= render "layouts/admin/menu" %>
        <%= render "layouts/admin/header" %>
        <%= yield %>
        <%= render "layouts/admin/footer" %>
      </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gentelella/1.4.0/js/custom.js"></script>
  </body>
</html>