config/routes.rb
Rails.application.routes.draw do
  post "/rate", to: "rater#create", as: "rate"
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  scope "(:locale)", locale: /en|vi/ do
    root to: "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"

    devise_scope :user do
      resources :users do
        resources :borrows
        member do
          get :following, :followers
        end
      end
    end

    resources :follow_books, only: [:create, :destroy]
    resources :relationships, only: [:create, :destroy]
    resources :like_books, only: [:create, :destroy]

    resources :books, only: %i(index show) do
      resources :comments, only: [:create, :destroy]
    end
    namespace :admin do
      resources :users
      resources :books
      resources :borrows
      resources :categories
      resources :statistics, only: [:index]
    end
  end
end

app/models/borrow.rb
class Borrow < ApplicationRecord
  after_create_commit :notify
  enum status: %i(waiting approved disapproved done)

  belongs_to :book
  belongs_to :user

  validates :started_at, presence: true
  validates :finished_at, presence: true
  validates :book_id, presence: true
  validates :user_id, presence: true
  validates :status, presence: true
  validate :validate_time, on: :create
  delegate :name, to: :user, prefix: true
  delegate :name, to: :book, prefix: true

  scope :select_attr, ->{select(:id, :user_id, :book_id, :started_at,
    :finished_at, :status)}
  scope :find_by_status, ->(book_id, finished_at){
    where "started_at < ? and book_id = ? and status = ?", finished_at, book_id, Settings.waiting
  }
  scope :search_scope, ->(status, search){
    joins(:book, :user).where(status: "#{status}")
    .where("books.name like '%#{search}%' or users.name like '%#{search}%'")
  }
  scope :check_record, ->(user_id, book_id){where user_id: user_id, book_id: book_id, status: [:waiting] }
  scope :status_approved, ->{where(status: [:approved]).where("finished_at < ?", DateTime.now)}
  scope :group_date, ->{group(:status).group "date(#{:created_at})"}

  class << self
    def search search, status
      if search
        search_scope search, status
      else
        Borrow.select_attr
      end
    end
  end

  private

  def notify
    Notification.create event: I18n.t("borrows.request", user_name: user.name), user_id: user.id
  end

  def validate_time
    errors.add(:started_at, "can't be in the past") unless started_at > DateTime.now
    errors.add(:started_at, "can't be > finished_at") unless started_at < finished_at
  end
end

app/controllers/admin/borrows_controller.rb
module Admin
  class BorrowsController < BaseController
    before_action :find_borrow, :find_book, only: :update

    def index
      @borrows = Borrow.select_attr.page(params[:page]).per(Settings.per_page)
        .search params[:status], params[:search]
    end

    def update
      if @borrow.update_attributes borrow_params
        flash[:success] = t "update_success"
        update_book_and_other_borrow
      else
        flash[:danger] = t "update_fail"
      end
      redirect_to admin_borrows_path
    end

    private

    def borrow_params
      params.require(:borrow).permit :user_id, :book_id, :started_at,
        :finished_at, :status
    end

    def update_book_and_other_borrow
      if params[:borrow][:status] == Settings.approved
        @book.update_attributes status: Book.statuses[:borrowed]
        @borrows = Borrow.find_by_status @book.id, @borrow.finished_at
        @borrows.update status: Settings.disapproved
        @borrows.each do |borrow|
          DisapprovedRequestMailer.delay.disapproved_request_email borrow.user
        end
      elsif params[:borrow][:status] == Settings.disapproved
        DisapprovedRequestMailer.delay.disapproved_request_email @borrow.user
        @book.update_attributes status: Book.statuses[:ready]
      else
        @book.update_attributes status: Book.statuses[:ready]
      end
    end

    def find_borrow
      return if @borrow = Borrow.find_by(id: params[:id])
      flash[:danger] = t "borrow.find.fail"
      redirect_to admin_borrows_path
    end

    def find_book
      return if @book = Book.find_by(id: @borrow.book_id)
      flash[:danger] = t "book.find.fail"
      redirect_to admin_borrows_path
    end
  end
end

app/controllers/borrows_controller.rb
class BorrowsController < ApplicationController
  before_action :find_borrow, only: :destroy

  def index
    @borrows = current_user.borrows.select_attr.page(params[:page]).per Settings.book_per_page
  end

  def new; end

  def create
    if Borrow.check_record(params[:borrow][:user_id], params[:borrow][:book_id]).present?
      flash[:danger] = t "borrows.already_exist"
      redirect_to books_path
    else
      create_borrow
    end
  end

  def destroy
    if @borrow.destroy
      flash[:success] = "borrows.delete_successfully"
    else
      flash[:danger] = "borrows.delete_fail"
    end
    redirect_to user_borrows_path
  end

  private

  def borrow_params
    params.require(:borrow).permit :user_id, :book_id, :started_at,
      :finished_at, :status
  end

  def find_borrow
    return if @borrow = Borrow.find_by(id: params[:id])
    flash[:danger] = t "users.find_fail"
    redirect_to user_borrows_path
  end

  def create_borrow
    @borrow = Borrow.new borrow_params
    if @borrow.save
      flash[:success] = t "borrows.created"
      redirect_to book_path @borrow.book
    else
      flash[:danger] = t "borrows.created_fail"
      redirect_to books_path
    end
  end
end

app/helpers/borrows_helper.rb
module BorrowsHelper
  def status_choice
    Borrow.statuses.keys.map{|status| [t("#{status}"), status]}
  end
end

app/views/borrows/_borrow.html.erb
<tr>
  <td><%= borrow.book_name %></td>
  <td><%= borrow.started_at %></td>
  <td><%= borrow.finished_at %></td>
  <td><%= borrow.status %></td>
  <td>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg-<%= borrow.id %>">
      <%= t "borrows.edit_borrow" %>
    </button>
  </td>
  <td>
    <%= link_to t("comments.delete"), user_borrow_path(current_user, borrow),method: :delete,
      data: {confirm: t("comments.you_sure")}, class: "btn btn-danger" %>
  </td>
</tr>
<%= render "modal", borrow: borrow %>

app/views/borrows/_modal.html.erb
<div class="modal fade bs-example-modal-lg-<%= borrow.id %>" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel"><%= t "categories.edit_category" %></h4>
      </div>
      <%= form_for [current_user, borrow], class: "form-horizontal form-label-left" do |f| %>
        <div class="col-md-12">
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <%= f.label :started_at, t("books.started_at"), class: "label-control" %>
                <%= f.text_field :started_at, class: "form-control datetimepicker datetimepicker1",
                  required: true %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <%= f.label :finished_at, t("books.finished_at"), class: "label-control" %>
                <%= f.text_field :finished_at, class: "form-control datetimepicker datetimepicker2",
                  required: true %>
              </div>
            </div>
          </div>
        </div>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.hidden_field :book_id, value: borrow.book.id %>
        <%= f.hidden_field :status, value: "waiting" %>
        <div class="ln_solid col-sm-12"></div>
        <div class="form-group">
          <div class="col-sm-6 offset-sm-3">
            <%= f.submit t("books.borrow"), class: "btn btn-block btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/borrows/index.html.erb
<div class="main main-raised">
  <div class="section section-basic custom-background">
    <div class="container style-container">
      <div class="right_col" role="main">
        <div>
          <div class="row top_tiles margin10">
            <div class="col-md-12 col-sm-12 col-xs-12 tile">
              <ul class="users">
                <table class="table">
                  <tr>
                    <th><%= t "users.new.name" %></th>
                    <th><%= t "borrows.started_at" %></th>
                    <th><%= t "borrows.finished_at" %></th>
                    <th><%= t "borrows.status" %></th>
                    <th></th>
                    <th></th>
                  </tr>
                  <%= render @borrows %>
                </table>
              </ul>
              <div class="col-sm-8 col-sm-offset-3">
                <%= paginate @borrows, theme: "twitter-bootstrap-3" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>